# Chassis Configuration

# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx.
# Domain names must use the `.local` TLD.
hosts:
  - sitemaps.local

# Should we use multisite?
multisite: No

# Set database values to save the prefix so Chassis doesn't freak out on
# re-provisions after tests.
database:
  name: wordpress
  user: wordpress
  password: password
  prefix: wp_

# Site Configuration
# (When overriding, include all values)
site:
  name: Core Sitemaps

# Install a list of extensions automatically
extensions:
  - chassis/chassis_xhgui
  - chassis/composer
  - chassis/memcache
  - chassis/nodejs
  - chassis/sequelpro
  - chassis/xdebug

# Testier - Use composer for test suite
# OpenSSL - Conflicts with XHgui
disabled_extensions:
  - chassis/tester
  - chassis/chassis_openssl

php: 7.3

virtualbox:
  memory: 2048

admin:
  user: wordpress
  email: wordpress@sitemaps.local
  password: password
